/* =============================================
   CLASSIC AURA — Product Catalog
   ============================================= */

const PRODUCTS = [

  // ─── FASHION (8) ───

  {
    id: 'velvet-blazer',
    name: 'Velvet Blazer',
    category: 'fashion',
    price: 5890,
    stock: 25,
    imageSeed: 'velvet-blazer-f',
    image: 'https://picsum.photos/seed/velvet-blazer-f/400/500',
    shortDescription: 'Luxurious velvet blazer with notch lapels and a tailored fit. Perfect for evening sophistication.',
    variants: [
      { label: 'S', value: 'S' },
      { label: 'M', value: 'M' },
      { label: 'L', value: 'L' },
      { label: 'XL', value: 'XL' },
    ],
  },
  {
    id: 'silk-midi-dress',
    name: 'Silk Midi Dress',
    category: 'fashion',
    price: 4250,
    stock: 30,
    imageSeed: 'silk-midi-dress-f',
    image: 'https://picsum.photos/seed/silk-midi-dress-f/400/500',
    shortDescription: 'Flowing silk midi dress in champagne blush. Effortless elegance with a flattering A-line silhouette.',
    variants: [
      { label: 'S', value: 'S' },
      { label: 'M', value: 'M' },
      { label: 'L', value: 'L' },
      { label: 'XL', value: 'XL' },
    ],
  },
  {
    id: 'floral-maxi-dress',
    name: 'Floral Maxi Dress',
    category: 'fashion',
    price: 3450,
    stock: 20,
    imageSeed: 'floral-maxi-f',
    image: 'https://picsum.photos/seed/floral-maxi-f/400/500',
    shortDescription: 'A romantic floral maxi in lightweight viscose. Elastic waist and voluminous sleeves.',
    variants: [
      { label: 'S', value: 'S' },
      { label: 'M', value: 'M' },
      { label: 'L', value: 'L' },
      { label: 'XL', value: 'XL' },
    ],
  },
  {
    id: 'embroidered-kurti',
    name: 'Embroidered Kurti',
    category: 'fashion',
    price: 2650,
    stock: 3,
    imageSeed: 'kurti-f',
    image: 'https://picsum.photos/seed/kurti-f/400/500',
    shortDescription: 'Hand-embroidered cotton kurti with delicate threadwork. Effortless daytime elegance.',
    variants: [
      { label: 'S', value: 'S' },
      { label: 'M', value: 'M' },
      { label: 'L', value: 'L' },
      { label: 'XL', value: 'XL' },
    ],
  },
  {
    id: 'crepe-abaya',
    name: 'Crepe Abaya',
    category: 'fashion',
    price: 4800,
    stock: 15,
    imageSeed: 'abaya-f',
    image: 'https://picsum.photos/seed/abaya-f/400/500',
    shortDescription: 'Flowful crepe abaya with clean lines and a modern cut. Lightweight yet structured.',
    variants: [
      { label: 'S', value: 'S' },
      { label: 'M', value: 'M' },
      { label: 'L', value: 'L' },
      { label: 'XL', value: 'XL' },
    ],
  },
  {
    id: 'cashmere-wrap-top',
    name: 'Cashmere Wrap Top',
    category: 'fashion',
    price: 3200,
    stock: 5,
    imageSeed: 'wrap-top-f',
    image: 'https://picsum.photos/seed/wrap-top-f/400/500',
    shortDescription: 'Sumptuous cashmere-blend wrap top with a draped neckline. Effortless luxury.',
    variants: [
      { label: 'S', value: 'S' },
      { label: 'M', value: 'M' },
      { label: 'L', value: 'L' },
      { label: 'XL', value: 'XL' },
    ],
  },
  {
    id: 'wide-leg-trousers',
    name: 'Wide-Leg Trousers',
    category: 'fashion',
    price: 3800,
    stock: 18,
    imageSeed: 'trousers-f',
    image: 'https://picsum.photos/seed/trousers-f/400/500',
    shortDescription: 'High-waisted wide-leg trousers in premium wool-blend. A staple for the modern wardrobe.',
    variants: [
      { label: 'S', value: 'S' },
      { label: 'M', value: 'M' },
      { label: 'L', value: 'L' },
      { label: 'XL', value: 'XL' },
    ],
  },
  {
    id: 'linen-blend-shirt',
    name: 'Linen Blend Shirt',
    category: 'fashion',
    price: 2200,
    stock: 35,
    imageSeed: 'linen-shirt-f',
    image: 'https://picsum.photos/seed/linen-shirt-f/400/500',
    shortDescription: 'Breathable linen-cotton shirt with a relaxed fit. An effortless everyday essential.',
    variants: [
      { label: 'S', value: 'S' },
      { label: 'M', value: 'M' },
      { label: 'L', value: 'L' },
      { label: 'XL', value: 'XL' },
    ],
  },

  // ─── COSMETICS (8) ───

  {
    id: 'radiant-foundation',
    name: 'Radiant Foundation',
    category: 'cosmetics',
    price: 1850,
    stock: 22,
    imageSeed: 'foundation-c',
    image: 'https://picsum.photos/seed/foundation-c/400/500',
    shortDescription: 'Buildable, luminous foundation with medium coverage and a natural satin finish. Vitamin E enriched.',
    variants: [
      { label: 'Ivory', value: 'ivory' },
      { label: 'Sand', value: 'sand' },
      { label: 'Honey', value: 'honey' },
      { label: 'Caramel', value: 'caramel' },
    ],
  },
  {
    id: 'rose-velvet-lipstick',
    name: 'Rose Velvet Lipstick',
    category: 'cosmetics',
    price: 1200,
    stock: 4,
    imageSeed: 'lipstick-c',
    image: 'https://picsum.photos/seed/lipstick-c/400/500',
    shortDescription: 'Long-wearing matte lipstick in a timeless rose shade. Creamy formula, stays comfortable all day.',
    variants: [
      { label: 'Crimson', value: 'crimson' },
      { label: 'Rose', value: 'rose' },
      { label: 'Nude', value: 'nude' },
      { label: 'Berry', value: 'berry' },
    ],
  },
  {
    id: 'volumizing-mascara',
    name: 'Volumizing Mascara',
    category: 'cosmetics',
    price: 950,
    stock: 28,
    imageSeed: 'mascara-c',
    image: 'https://picsum.photos/seed/mascara-c/400/500',
    shortDescription: 'Intense black mascara that builds dramatic volume without clumping. Smudge-proof and long-lasting.',
    variants: [
      { label: 'Black', value: 'black' },
      { label: 'Brown Black', value: 'brown-black' },
    ],
  },
  {
    id: 'hd-setting-powder',
    name: 'HD Setting Powder',
    category: 'cosmetics',
    price: 1400,
    stock: 2,
    imageSeed: 'powder-c',
    image: 'https://picsum.photos/seed/powder-c/400/500',
    shortDescription: 'Micro-fine translucent powder that sets makeup flawlessly. Blurs pores without flashback.',
    variants: [
      { label: 'Translucent', value: 'translucent' },
      { label: 'Light', value: 'light' },
      { label: 'Medium', value: 'medium' },
      { label: 'Deep', value: 'deep' },
    ],
  },
  {
    id: 'rosewater-face-mist',
    name: 'Rosewater Face Mist',
    category: 'cosmetics',
    price: 750,
    stock: 40,
    imageSeed: 'face-mist-c',
    image: 'https://picsum.photos/seed/face-mist-c/400/500',
    shortDescription: 'Hydrating rosewater mist that refreshes and soothes. Distilled from damask roses.',
    variants: [
      { label: '50 ml', value: '50ml' },
      { label: '100 ml', value: '100ml' },
    ],
  },
  {
    id: 'nude-eyeshadow-palette',
    name: 'Nude Eyeshadow Palette',
    category: 'cosmetics',
    price: 2200,
    stock: 12,
    imageSeed: 'eyeshadow-c',
    image: 'https://picsum.photos/seed/eyeshadow-c/400/500',
    shortDescription: 'A curated palette of 12 warm nude tones. Velvety mattes and luminous shimmers in one.',
    variants: [
      { label: 'Warm Nudes', value: 'warm' },
      { label: 'Cool Nudes', value: 'cool' },
    ],
  },
  {
    id: 'hydra-glow-serum',
    name: 'Hydra Glow Serum',
    category: 'cosmetics',
    price: 2800,
    stock: 16,
    imageSeed: 'serum-c',
    image: 'https://picsum.photos/seed/serum-c/400/500',
    shortDescription: 'Lightweight hyaluronic acid serum with vitamin C. Plumps, brightens, and restores radiance.',
    variants: [
      { label: '30 ml', value: '30ml' },
      { label: '50 ml', value: '50ml' },
    ],
  },
  {
    id: 'velvet-liquid-lip',
    name: 'Velvet Liquid Lip',
    category: 'cosmetics',
    price: 1100,
    stock: 25,
    imageSeed: 'liquid-lip-c',
    image: 'https://picsum.photos/seed/liquid-lip-c/400/500',
    shortDescription: 'Transfer-proof liquid lipstick with a velvet matte finish. Intense colour that lasts 12 hours.',
    variants: [
      { label: 'Mauve', value: 'mauve' },
      { label: 'Terracotta', value: 'terracotta' },
      { label: 'Dusty Rose', value: 'dusty-rose' },
      { label: 'Wine', value: 'wine' },
    ],
  },

  // ─── Maroon Embroidered Kurti Set ───
  {
    id: 'maroon-embroidered-kurti-set',
    name: 'Maroon Embroidered Kurti Set',
    category: 'fashion',
    price: 1550,
    stock: 7,
    imageSeed: 'maroon-kurti-set',
    image: 'images/kurti.png',
    shortDescription: 'A gorgeous maroon kurti set with intricate floral embroidery, flowy bell sleeves, and delicate pom-pom trim detailing. Paired with a matching straight-cut trouser — perfect for festive occasions, office wear, or everyday elegance.',
    variants: [
      { label: 'L', value: 'L' },
      { label: 'XL', value: 'XL' },
      { label: 'XXL', value: 'XXL' },
    ],
  },

  // ─── Fashion Herbs Mango Nourishing Bleach ───
  {
    id: 'mango-nourishing-bleach',
    name: 'Fashion Herbs Mango Nourishing Bleach',
    category: 'cosmetics',
    price: 180,
    stock: 3,
    originalPrice: 250,
    image: 'images/mengo.jpg',
    rating: 4.5,
    reviewCount: 128,
    shortDescription: 'Premium herbal bleaching solution enriched with the natural goodness of mango extracts and therapeutic herbal essences. Delivers a radiant, golden-toned glow while gently nourishing your skin.',
    fullDescription: [
      '<strong>Fashion Herbs Therapy Mango Nourishing Bleach</strong> is a premium herbal bleaching solution enriched with the natural goodness of mango extracts and therapeutic herbal essences. Designed for the modern woman who values both beauty and skin safety, this bleach delivers a radiant, golden-toned glow while gently nourishing your skin.',
      'Unlike harsh chemical bleaches, this formula includes a dedicated <strong>Pre-Bleach Therapy Cream</strong> that prepares and protects your skin before the bleaching process. The pre-bleach cream deeply moisturises and creates a protective barrier, preventing irritation, redness, and sensitivity &mdash; making it suitable even for delicate facial skin.',
      'Whether you want to reduce sun tan, even out skin tone, or simply achieve a brighter complexion, this mango-infused blend works gently yet effectively. The herbal essences ensure your skin stays soft, supple, and nourished long after application.',
      '<strong>Key Ingredients:</strong> Mango Extracts, Herbal Essences, Pre-Bleach Therapy Cream. Country of Origin: India. Suitable for all skin types.',
    ],
    benefits: [
      { icon: 'smile', text: '<strong>Natural Radiance &amp; Glow:</strong> Instantly brightens skin with a healthy, golden-toned glow.' },
      { icon: 'sun', text: '<strong>Sun Tan &amp; Dark Spot Removal:</strong> Reduces sun tan, uneven skin tone, and dark spots.' },
      { icon: 'zap', text: '<strong>Facial Hair Blending:</strong> Bleaches facial hair to match natural skin tone smoothly.' },
      { icon: 'shield', text: '<strong>Pre-Bleach Therapy Protection:</strong> Special pre-bleach cream that deeply nourishes skin and prevents irritation.' },
    ],
    badges: [
      { icon: 'globe', text: 'Country: India' },
      { icon: 'droplet', text: 'All Skin Types' },
      { icon: 'leaf', text: 'Mango + Herbal' },
    ],
    ingredients: [
      { icon: 'leaf', name: 'Mango Extracts', description: 'Rich in vitamins A &amp; C for natural radiance and skin nourishment.' },
      { icon: 'leaf', name: 'Herbal Essences', description: 'Gentle botanical blend that soothes and protects the skin barrier.' },
      { icon: 'shield', name: 'Pre-Bleach Cream', description: 'Deep-nourishing formula that prevents irritation during bleaching.' },
    ],
    usageSteps: [
      { title: 'Cleanse', description: 'Wash your face thoroughly and pat dry before application.' },
      { title: 'Apply Pre-Bleach Cream', description: 'Spread the pre-bleach therapy cream evenly across the area. Leave for 2-3 minutes.' },
      { title: 'Mix &amp; Apply Bleach', description: 'Mix the bleach cream and activator as directed. Apply evenly over the pre-bleach layer.' },
      { title: 'Wait 10-15 Minutes', description: 'Do not exceed the recommended time. Rinse off with lukewarm water.' },
      { title: 'Moisturise', description: 'Apply a gentle moisturiser after rinsing for best results.' },
    ],
    variants: [
      { label: 'With Pre-Bleach', value: 'with-pre-bleach' },
    ],
    whatsapp: { enabled: true, phone: '8801924904441' },
  },
];
